Automatically use the OS string from uname -r instead of requiring that it be specified; also check that the files it depends on are built.

diff --git a/runit b/runit
--- a/runit
+++ b/runit
@@ -23,13 +23,16 @@
 #
 # Note that you should use multiview to construct the HTML reports separately.
 
-if [ -z "$1" ]; then
-    echo "Please provide the version of RHEL (e.g. 'rhel6.3')"
-    exit 1
-fi
+OSVER=`uname -r`
 ROOT_UID=0   # Only users with $UID 0 have root privileges.
 HN=`hostname -s`
 DN=`dirname $0`
+
+if [ ! -x "$DN/bin/tattle" ]; then
+    echo "Could not find runnable tattle: $DN/bin/tattle"
+    exit 1
+fi
+
 VER=`$DN/bin/tattle -V`
 
 results="$DN/../results"
@@ -38,10 +41,20 @@ if [ ! -d "$results" ]; then
     exit 1
 fi
 
-if [ -z "$2" ]; then
+if [ ! -x "$DN/bench" ]; then
+    echo "Could not find runnable bench: $DN/bench"
+    exit 1
+fi
+
+if [ ! -x "$DN/multiview" ]; then
+    echo "Could not find runnable multiview: $DN/multiview"
+    exit 1
+fi
+
+if [ -z "$1" ]; then
 	suite="full"
 else
-	suite=$2
+	suite=$1
 fi
 
 #
@@ -52,7 +65,7 @@ fi
 coreid=$(lscpu -p | tail -1 | awk '{ split($0, array, ","); print array[1]; }')
 nodeid=$(lscpu -p | tail -1 | awk '{ split($0, array, ","); print array[4]; }')
 
-template_base="$results/$1-$HN-$suite"
+template_base="$results/$OSVER-$HN-$suite"
 template_nonuma="$template_base-nonuma-lm.$VER"
 template_numa="$template_base-numa.N$nodeid.m$nodeid-lm.$VER"
 template_core="$template_base-core.C$coreid.m$nodeid-lm.$VER"
